/* generated by tools/web_abi_shims.py; see there */

extern void debug_free(int, int, int);
int web_abi_debug_free__i32_i32_i32__i32(int a0, int a1, int a2)
{
	debug_free((int)a0, (int)a1, (int)a2);
	return 0;
}

extern int editor_preprocess_rendered_object(void);
int web_abi_editor_preprocess_rendered_object__i32_i32__i32(int a0, int a1)
{
	(void)a0;
	(void)a1;
	return (int)editor_preprocess_rendered_object();
}

static int web_abi_no_arguments[4];
extern void error(int, int, int *);
int web_abi_error__i32_i32__i32(int a0, int a1)
{
	error(a0, a1, web_abi_no_arguments);
	return 0;
}

extern void game_engine_override_map_name(int);
int web_abi_game_engine_override_map_name__i32__i32(int a0)
{
	game_engine_override_map_name((int)a0);
	return 0;
}

extern void game_show_score_extended(int, int, int);
int web_abi_game_show_score_extended__i32_i32_i32__i32(int a0, int a1, int a2)
{
	game_show_score_extended((int)a0, (int)a1, (int)a2);
	return 0;
}

extern void game_show_score_you_ally_enemy(int, int, int, int, int);
int web_abi_game_show_score_you_ally_enemy__i32_i32_i32_i32_i32__i32(int a0, int a1, int a2, int a3, int a4)
{
	game_show_score_you_ally_enemy((int)a0, (int)a1, (int)a2, (int)a3, (int)a4);
	return 0;
}

extern void input_abstraction_update(void);
int web_abi_input_abstraction_update__v__i32(void)
{
	input_abstraction_update();
	return 0;
}

extern void interface_draw_screen(void);
int web_abi_interface_draw_screen__v__i32(void)
{
	interface_draw_screen();
	return 0;
}

extern long long lseek(int, long long, int);
int web_abi_lseek__i32_i32_i32__i32(int a0, int a1, int a2)
{
	return (int)lseek((int)a0, (long long)a1, (int)a2);
}

extern void main_set_multiplayer_map_name(int);
int web_abi_main_set_multiplayer_map_name__i32__i32(int a0)
{
	main_set_multiplayer_map_name((int)a0);
	return 0;
}

extern void matrix3x3_rotation_to_quaternion(int, int);
int web_abi_matrix3x3_rotation_to_quaternion__i32_i32__i32(int a0, int a1)
{
	matrix3x3_rotation_to_quaternion((int)a0, (int)a1);
	return 0;
}

extern void network_game_abort(void);
int web_abi_network_game_abort__v__i32(void)
{
	network_game_abort();
	return 0;
}

extern void network_game_generate_join_game_token(int);
int web_abi_network_game_generate_join_game_token__i32__i32(int a0)
{
	network_game_generate_join_game_token((int)a0);
	return 0;
}

extern void network_game_server_change_game_variant(int, int);
int web_abi_network_game_server_change_game_variant__i32_i32__i32(int a0, int a1)
{
	network_game_server_change_game_variant((int)a0, (int)a1);
	return 0;
}

extern void network_game_server_change_map_name(int, int);
int web_abi_network_game_server_change_map_name__i32_i32__i32(int a0, int a1)
{
	network_game_server_change_map_name((int)a0, (int)a1);
	return 0;
}

extern void periodic_functions_dispose(void);
int web_abi_periodic_functions_dispose__v__i32(void)
{
	periodic_functions_dispose();
	return 0;
}

extern void periodic_functions_initialize(void);
int web_abi_periodic_functions_initialize__v__i32(void)
{
	periodic_functions_initialize();
	return 0;
}

extern int player_control_get_facing_direction(int, int);
void web_abi_player_control_get_facing_direction__i32_i32__void(int a0, int a1)
{
	player_control_get_facing_direction((int)a0, (int)a1);
}

extern void props_dispose_from_old_map(void);
int web_abi_props_dispose_from_old_map__v__i32(void)
{
	props_dispose_from_old_map();
	return 0;
}

extern void qsort_4byte(int, int, int);
int web_abi_qsort_4byte__i32_i32_i32__i32(int a0, int a1, int a2)
{
	qsort_4byte((int)a0, (int)a1, (int)a2);
	return 0;
}

extern void random_math_dispose(void);
int web_abi_random_math_dispose__v__i32(void)
{
	random_math_dispose();
	return 0;
}

extern void random_math_initialize(void);
int web_abi_random_math_initialize__v__i32(void)
{
	random_math_initialize();
	return 0;
}

extern void rasterizer_draw_dynamic_triangles_static_vertices(int, int, int, int);
int web_abi_rasterizer_draw_dynamic_triangles_static_vertices__i32_i32_i32_i32__i32(int a0, int a1, int a2, int a3)
{
	rasterizer_draw_dynamic_triangles_static_vertices((int)a0, (int)a1, (int)a2, (int)a3);
	return 0;
}

extern void rasterizer_initialize_for_new_map(void);
int web_abi_rasterizer_initialize_for_new_map__v__i32(void)
{
	rasterizer_initialize_for_new_map();
	return 0;
}

extern int rasterizer_preinitialize__fill_you_up_with_the_devils_cock(void);
void web_abi_rasterizer_preinitialize__fill_you_up_with_the_devils_cock__v__void(void)
{
	rasterizer_preinitialize__fill_you_up_with_the_devils_cock();
}

extern int rasterizer_set_texture(int, int, int, int, int);
void web_abi_rasterizer_set_texture__i32_i32_i32_i32_i32__void(int a0, int a1, int a2, int a3, int a4)
{
	rasterizer_set_texture((int)a0, (int)a1, (int)a2, (int)a3, (int)a4);
}

extern int rasterizer_set_texture_bitmap_data(int, int);
void web_abi_rasterizer_set_texture_bitmap_data__i32_i32__void(int a0, int a1)
{
	rasterizer_set_texture_bitmap_data((int)a0, (int)a1);
}

extern void render_debug_line(int, int, int, int);
int web_abi_render_debug_line__i32_i32_i32_i32__i32(int a0, int a1, int a2, int a3)
{
	render_debug_line((int)a0, (int)a1, (int)a2, (int)a3);
	return 0;
}

extern void saved_game_file_remember_last_used_multiplayer_map(int);
int web_abi_saved_game_file_remember_last_used_multiplayer_map__i32__i32(int a0)
{
	saved_game_file_remember_last_used_multiplayer_map((int)a0);
	return 0;
}

extern long long time(long long *);
int web_abi_time__i32__i32(int *a0)
{
	long long now = time((long long *)0);

	if (a0)
		*a0 = (int)now;
	return (int)now;
}

extern void widget_free(int);
int web_abi_widget_free__i32__i32(int a0)
{
	widget_free((int)a0);
	return 0;
}

extern void xbox_demos_launch(void);
int web_abi_xbox_demos_launch__v__i32(void)
{
	xbox_demos_launch();
	return 0;
}
